places=[{"placeName":"Walt Disney World","description":"A family-oriented theme park based on Disney movies, shows or characters. ","latitude":28.421389,"longitude":-81.580687},
{"placeName":"Everglades National Park","description":"A national wetland preserve that provides a home for many endangered animals.","latitude":25.823088,"longitude":-80.550106},
{"placeName":"Kennedy Space Center","description":"One of ten National Aeronautics and Space Administration field centers where people of all ages can see space shuttles up close. ","latitude":28.573079,"longitude":-80.648219},
{"placeName":"Universal Studios","description":"A theme park and production studio featuring rides based on movies and TV. ","latitude":28.479206,"longitude":-81.468484},
{"placeName":"Miami Beach Art Deco Historic District","description":" The nation's largest concentration of Art Deco architecture, which features over 900 historic buildings.","latitude":25.780385,"longitude":-80.130068},
{"placeName":"Daytona International Speedway","description":"A race track in Daytona Beach home of the Daytona 500.","latitude":29.185843,"longitude":-81.069061},
{"placeName":"Sea World","description":"A marine theme park where tourists can experience up-close animal encounters.","latitude":28.411616,"longitude":-81.461265},
{"placeName":"Busch Gardens","description":"A Tampa amusement park with roller coasters and animal attractions.","latitude":28.037855,"longitude":-82.418802},
{"placeName":"Dry Tortugas National Park","description":"A national park that preserves Fort Jefferson and the seven Dry Tortugas islands.","latitude":24.628581,"longitude":-82.873225},
{"placeName":"Castillo De San Marcos","description":"The oldest and largest masonry fort in the continental United States.","latitude":29.898066,"longitude":-81.310735},
{"placeName":"Edison & Ford Winter Estates","description":" A historical museum and 21 acre botanical garden near the houses of Thomas Edison and Henry Ford.","latitude":26.63455,"longitude":-81.879538},
{"placeName":"Circus Museum at The Ringling","description":"A museum documenting American circus history.","latitude":27.387432,"longitude":-82.562694},
{"placeName":"Salvador Dalí Museum","description":"An art museum dedicated to the work of Salvador Dalí.","latitude":27.766212,"longitude":-82.630978},
{"placeName":"Legoland","description":"A family theme park focused on the Lego toy.","latitude":27.989744,"longitude":-81.688783},
{"placeName":"Clearwater Marine Aquarium","description":"An aquarium dedicated to the rescue of sick and injured marine animals.","latitude":27.977177,"longitude":-82.818351},
{"placeName":"The Florida Aquarium","description":"An aquarium that allows people to see aquatic animals from all over the world. ","latitude":27.944162,"longitude":-82.444413},
{"placeName":"Jacksonville Zoo and Gardens","description":"An award-winning zoo with tons of animals and a varitety of activities for kids. ","latitude":30.402445,"longitude":-81.642539},
{"placeName":"Cirque Du Soleil","description":"A circus show with acrobats, contortionists and other exciting sites.","latitude":28.370843,"longitude":-81.522604},
{"placeName":"Mai Kai Restaurant","description":"A local landmark that serves Chinese fare, tropical drinks & a Polynesian floor show.","latitude":26.172559,"longitude":-80.119425},
{"placeName":"Ocala Drive-In","description":"An old-fashioned drive-in movie theater with the latest movies.","latitude":29.138301,"longitude":-82.110438}]
